### ISSUE TITLE
How to AddSpacer in the Group?

### ISSUE THREAD

**Issue by painezeng** [codestack-net-dev/sw-dev-tools-addin#9]
if we  have many commands , we want use addspacer2 to add spacer? can you add it? or add sub group for   some commands group.

**Comment by codestackdev** [comment]
I think the best option to implement spacer would be to add SpacerAttribute with option to add spacer after the command this attribute is added to or before

For the sub menus I think it would be better to allow specifying parent menu in the AddCommands method.

**Comment by codestackdev** [comment]
Implemented in 0.7.5: https://www.codestack.net/labs/solidworks/swex/add-in/commands-manager/sub-menu-and-spacers#adding-spacer

**Comment by painezeng** [comment]
thanks
